import { StyleSheet } from "react-native";

// Extracted from ExpenseReviewSheet.jsx. It was a fixed white sheet with navy
// text, so on the dark theme a scanned receipt opened a full light panel over
// the dark camera screen.
export const createStyles = (c) =>
  StyleSheet.create({
    backdrop: {
      flex: 1,
      backgroundColor: "rgba(5,45,80,0.35)",
      justifyContent: "flex-end",
    },
    sheet: {
      backgroundColor: c.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 24,
      maxHeight: "90%",
    },
    handle: {
      alignSelf: "center",
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: c.divider,
      marginBottom: 12,
    },
    title: {
      fontSize: 20,
      fontWeight: "700",
      color: c.textPrimary,
      marginBottom: 12,
    },
    preview: {
      width: "100%",
      height: 160,
      borderRadius: 14,
      backgroundColor: c.surfaceMuted,
      marginBottom: 14,
    },
    label: {
      color: c.textSecondary,
      fontSize: 13,
      marginBottom: 6,
      marginTop: 10,
    },
    input: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: c.textPrimary,
    },
    row: { flexDirection: "row", gap: 12 },
    col: { flex: 1 },
    projectFixed: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    projectFixedText: { color: c.textPrimary, fontSize: 15, fontWeight: "600" },
    projectList: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    projectChip: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    projectChipActive: { backgroundColor: "#0785F4", borderColor: "#0785F4" },
    projectChipText: { color: c.textPrimary, fontSize: 14 },
    projectChipTextActive: { color: "#fff", fontWeight: "600" },
    hint: { color: c.textMuted, fontSize: 13 },
    error: { color: c.danger, marginTop: 12 },
    actions: { flexDirection: "row", gap: 12, marginTop: 16 },
    cancelBtn: {
      flex: 1,
      height: 52,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
    },
    cancelText: { color: c.textSecondary, fontSize: 15, fontWeight: "600" },
    saveBtn: {
      flex: 2,
      height: 52,
      borderRadius: 16,
      backgroundColor: "#0785F4",
      alignItems: "center",
      justifyContent: "center",
    },
    saveText: { color: "#fff", fontSize: 15, fontWeight: "700" },
  });
