import { StyleSheet } from "react-native";

// Extracted from ToolActionSheet.jsx.
export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(5,45,80,0.35)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 28,
    maxHeight: "85%",
  },
  handle: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#CBD5E1",
    marginBottom: 14,
  },
  name: { fontSize: 20, fontWeight: "700", color: "#052D50" },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
  },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999 },
  badge_available: { backgroundColor: "rgba(22,163,94,0.14)" },
  badge_occupied: { backgroundColor: "rgba(7,133,244,0.14)" },
  badge_broken: { backgroundColor: "rgba(220,38,38,0.14)" },
  badge_in_repair: { backgroundColor: "rgba(234,166,35,0.16)" },
  badgeText: { fontSize: 13, fontWeight: "600", color: "#052D50" },
  holder: { color: "#5F7588", fontSize: 14, fontWeight: "600" },
  location: { color: "#5F7588", fontSize: 14, marginTop: 8 },
  qr: { color: "#94A3B8", fontSize: 13, fontFamily: "Courier", marginTop: 4 },
  actions: { flexDirection: "row", gap: 12, marginTop: 18 },
  primaryBtn: {
    flex: 2,
    height: 52,
    borderRadius: 16,
    backgroundColor: "#0785F4",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryText: { color: "#fff", fontSize: 15, fontWeight: "700" },
  secondaryBtn: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D8E0E8",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryText: { color: "#0785F4", fontSize: 15, fontWeight: "600" },
  historyBox: { marginTop: 14, maxHeight: 200 },
  historyEmpty: { color: "#94A3B8", fontSize: 14 },
  historyItem: {
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: "#e9e9e9",
  },
  historyType: { color: "#052D50", fontSize: 14, fontWeight: "600" },
  historyDate: { color: "#94A3B8", fontSize: 12, marginTop: 2 },
  closeBtn: {
    marginTop: 18,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1F5F9",
  },
  closeText: { color: "#5F7588", fontSize: 15, fontWeight: "600" },
});
