import { StyleSheet } from "react-native";

export const INK = "#052d50";
export const PRIMARY = "#2683f9";
export const MUTED = "#687898";
export const LINE = "#e7ecf0";
export const FIELD_BG = "#f4f7fa";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#EEEEEE", paddingTop: 48 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  title: { fontSize: 18, fontWeight: "800", color: INK },
  placeholder: { width: 40 },

  scroll: { paddingHorizontal: 15, paddingBottom: 190, gap: 13 },

  field: { gap: 5 },
  label: {
    fontSize: 12,
    fontWeight: "700",
    color: MUTED,
    marginLeft: 2,
  },
  input: {
    backgroundColor: FIELD_BG,
    borderWidth: 1,
    borderColor: LINE,
    borderRadius: 10,
    paddingHorizontal: 13,
    paddingVertical: 12,
    fontSize: 15,
    fontWeight: "600",
    color: INK,
    minHeight: 46,
  },
  inputRow: {
    backgroundColor: FIELD_BG,
    borderWidth: 1,
    borderColor: LINE,
    borderRadius: 10,
    paddingHorizontal: 13,
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  inputRowText: { fontSize: 15, fontWeight: "600", color: INK, flex: 1 },
  inputRowPlaceholder: { color: "#9fb0c4", fontWeight: "500" },
  textarea: { minHeight: 96, textAlignVertical: "top", paddingTop: 12 },

  heroLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginLeft: 2,
  },
  heroLabel: { fontSize: 13, fontWeight: "800", color: INK },
  heroMark: {
    fontSize: 9.5,
    fontWeight: "800",
    letterSpacing: 0.6,
    color: PRIMARY,
    backgroundColor: "rgba(38,131,249,0.14)",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
    overflow: "hidden",
    textTransform: "uppercase",
  },
  heroInput: {
    backgroundColor: "#fff",
    borderWidth: 1.5,
    borderColor: "rgba(38,131,249,0.42)",
    minHeight: 116,
  },

  two: { flexDirection: "row", gap: 11 },
  half: { flex: 1 },

  divider: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.6,
    color: MUTED,
    textTransform: "uppercase",
    marginTop: 4,
    marginBottom: 2,
    marginLeft: 2,
  },

  row: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: LINE,
    borderRadius: 14,
    padding: 12,
    gap: 9,
  },
  rowLabelLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowDescField: {
    backgroundColor: FIELD_BG,
    borderWidth: 1,
    borderColor: LINE,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
    fontSize: 14,
    fontWeight: "600",
    color: INK,
    minHeight: 42,
    textAlignVertical: "top",
  },
  rowDelete: { padding: 4 },
  rowGrid: { flexDirection: "row", gap: 8 },
  cell: { flex: 1, gap: 3 },
  cellLabel: { fontSize: 10.5, color: MUTED, fontWeight: "700" },
  cellInput: {
    backgroundColor: FIELD_BG,
    borderWidth: 1,
    borderColor: LINE,
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 7,
    fontSize: 13,
    fontWeight: "700",
    color: INK,
    textAlign: "right",
  },
  cellInputLeft: { textAlign: "left" },
  rowAmount: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    paddingTop: 2,
  },
  rowAmountLabel: { fontSize: 12, color: MUTED, fontWeight: "700" },
  rowAmountValue: { fontSize: 15, fontWeight: "800", color: INK },
  addRow: {
    borderWidth: 1,
    borderColor: "#b9c8d8",
    borderStyle: "dashed",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  addRowText: { color: PRIMARY, fontWeight: "700", fontSize: 14 },

  toggleRow: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: LINE,
    borderRadius: 14,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  toggleTitle: { fontSize: 14, fontWeight: "700", color: INK },
  toggleSub: { fontSize: 12, color: MUTED, marginTop: 2 },

  totals: {
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#eef2f6",
    padding: 15,
    gap: 7,
    marginTop: 2,
  },
  totalLine: { flexDirection: "row", justifyContent: "space-between" },
  totalLabel: { fontSize: 13.5, color: MUTED, fontWeight: "600" },
  totalValue: { fontSize: 13.5, fontWeight: "700", color: INK },
  totalValueNeg: { color: "#2fa84f" },
  grandLine: {
    borderTopWidth: 1,
    borderTopColor: "#eef2f6",
    marginTop: 3,
    paddingTop: 9,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  grandLabel: { fontSize: 15, fontWeight: "800", color: INK },
  grandValue: { fontSize: 19, fontWeight: "800", color: INK },

  actions: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 15,
    paddingTop: 12,
    paddingBottom: 30,
    backgroundColor: "#EEEEEE",
    borderTopWidth: 1,
    borderTopColor: "#e2e6ea",
  },
  btn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 7,
  },
  btnPrimary: { backgroundColor: PRIMARY },
  btnGhost: { backgroundColor: "#d9e9fb" },
  btnText: { fontSize: 14.5, fontWeight: "800" },
  btnTextPrimary: { color: "#fff" },
  btnTextGhost: { color: "#0785f4" },
  btnDisabled: { opacity: 0.5 },

  typeToggle: {
    flexDirection: "row",
    backgroundColor: "#dfe6ee",
    borderRadius: 11,
    padding: 4,
    marginBottom: 12,
  },
  typeBtn: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 8,
    alignItems: "center",
  },
  typeBtnOn: {
    backgroundColor: "#fff",
    shadowColor: INK,
    shadowOpacity: 0.12,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  typeText: { fontSize: 14, fontWeight: "700", color: MUTED },
  typeTextOn: { color: INK },

  /* client picker modal */
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(5,25,50,0.45)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 30,
    maxHeight: "82%",
  },
  grab: {
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#d5dee7",
    alignSelf: "center",
    marginBottom: 12,
  },
  modalTitle: { fontSize: 17, fontWeight: "800", color: INK, marginBottom: 12 },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: FIELD_BG,
    borderWidth: 1,
    borderColor: LINE,
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  searchInput: { flex: 1, paddingVertical: 11, fontSize: 15, color: INK },
  clientRow: {
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f3f6",
  },
  clientName: { fontSize: 15, fontWeight: "700", color: INK },
  clientMeta: { fontSize: 12.5, color: MUTED, marginTop: 2 },
  newClientBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 14,
  },
  newClientText: { color: PRIMARY, fontWeight: "800", fontSize: 15 },
});
