import { StyleSheet } from "react-native";

// Palette mirrors the admin panel: ink #052d50, primary #2683f9,
// muted #687898, borders #e7ecf0, status tones draft/sent/ok/bad.
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#EEEEEE",
    paddingTop: 48,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  title: {
    fontSize: 18,
    fontWeight: "800",
    color: "#052d50",
  },
  placeholder: { width: 40 },

  segmented: {
    flexDirection: "row",
    backgroundColor: "#dfe6ee",
    borderRadius: 13,
    padding: 4,
    marginHorizontal: 15,
    marginBottom: 12,
  },
  segBtn: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 10,
    alignItems: "center",
  },
  segBtnOn: {
    backgroundColor: "#fff",
    shadowColor: "#052d50",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  segText: { fontSize: 14, fontWeight: "700", color: "#687898" },
  segTextOn: { color: "#052d50" },

  pillsRow: { flexGrow: 0, marginBottom: 10, maxHeight: 40 },
  pillsContent: { paddingHorizontal: 15, gap: 7, alignItems: "center" },
  pill: {
    paddingVertical: 6,
    paddingHorizontal: 13,
    borderRadius: 999,
    backgroundColor: "transparent",
  },
  pillOn: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#052d50",
  },
  pillText: { fontSize: 12.5, fontWeight: "600", color: "rgba(5,45,80,0.5)" },
  pillTextOn: { color: "#052d50" },

  listContent: { paddingHorizontal: 15, paddingBottom: 150, gap: 11 },
  center: { paddingTop: 90, alignItems: "center", gap: 12 },
  emptyText: {
    fontSize: 14,
    color: "#687898",
    textAlign: "center",
    paddingHorizontal: 30,
  },

  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 15,
    gap: 6,
    shadowColor: "#072b4a",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  cardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardNo: { fontSize: 12, fontWeight: "600", color: "#687898" },
  cardCustomer: { fontSize: 15.5, fontWeight: "700", color: "#052d50" },
  cardBottom: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  cardMeta: { fontSize: 12.5, color: "#687898", flex: 1 },
  cardAmount: { fontSize: 15, fontWeight: "800", color: "#052d50" },

  badge: { paddingVertical: 4, paddingHorizontal: 9, borderRadius: 7 },
  badgeText: {
    fontSize: 10.5,
    fontWeight: "800",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  badge_draft: { backgroundColor: "#eef1f5" },
  badgeText_draft: { color: "#687898" },
  badge_sent: { backgroundColor: "#e6f0ff" },
  badgeText_sent: { color: "#1677ff" },
  badge_ok: { backgroundColor: "#e7f6ec" },
  badgeText_ok: { color: "#2fa84f" },
  badge_bad: { backgroundColor: "#fdecec" },
  badgeText_bad: { color: "#e5484d" },

  customerChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    marginHorizontal: 15,
    marginBottom: 10,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e7ecf0",
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 13,
    maxWidth: "90%",
  },
  customerChipText: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#052d50",
    flexShrink: 1,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(5,25,50,0.45)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 30,
    maxHeight: "70%",
  },
  grab: {
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#d5dee7",
    alignSelf: "center",
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#052d50",
    marginBottom: 8,
  },
  customerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f3f6",
    gap: 10,
  },
  customerRowText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#052d50",
    flex: 1,
  },
});
