import { StyleSheet } from "react-native";
import {
  standardScreenContainer,
  standardScreenHeader,
} from "../../../styles/screenLayout";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f2f1f6",
  },
  pageContainer: {
    ...standardScreenContainer,
    paddingBottom: 0,
  },
  contentScroll: {
    flex: 1,
    width: "100%",
  },
  contentContainer: {
    paddingBottom: 140,
    gap: 12,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f2f1f6",
  },
  loadingText: {
    marginTop: 12,
    color: "#698196",
  },
  accessDeniedContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    backgroundColor: "#f2f1f6",
  },
  accessDeniedText: {
    fontSize: 22,
    fontWeight: "700",
    color: "#052D50",
    marginBottom: 8,
  },
  accessDeniedSubtext: {
    fontSize: 15,
    color: "#698196",
    textAlign: "center",
    marginBottom: 24,
  },
  backButton: {
    backgroundColor: "#0091FF",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  backButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  header: {
    ...standardScreenHeader,
  },
  headerTitle: {
    color: "#052D50",
    fontSize: 17,
    fontFamily: "DMSans-SemiBold",
  },
  sectionLabel: {
    marginBottom: 8,
    marginTop: 8,
    paddingHorizontal: 8,
    color: "#698196",
    fontSize: 13,
    fontWeight: "600",
  },
  groupCard: {
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    borderRadius: 24,
    overflow: "hidden",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  groupRow: {
    minHeight: 60,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e9e9e9",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  groupRowLast: {
    borderBottomWidth: 0,
  },
  groupRowDisabled: {
    opacity: 0.45,
  },
  rowContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  rowIcon: {
    width: 27,
    height: 27,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  rowTextContainer: {
    flex: 1,
  },
  rowLabel: {
    color: "#698196",
    fontSize: 12,
    marginBottom: 2,
  },
  rowValue: {
    color: "#052D50",
    fontSize: 16,
  },
  rowPlaceholder: {
    color: "rgba(5, 45, 80, 0.45)",
  },
  rowHint: {
    color: "#698196",
    fontSize: 13,
    lineHeight: 18,
  },
  clearInlineButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(5, 45, 80, 0.06)",
  },
  inputWrapper: {
    width: "100%",
  },
  textAreaWrapper: {
    width: "100%",
  },
  inputLabel: {
    color: "#698196",
    fontSize: 12,
    marginBottom: 4,
  },
  input: {
    color: "#052D50",
    fontSize: 16,
    paddingVertical: 0,
  },
  textArea: {
    minHeight: 70,
    textAlignVertical: "top",
    paddingTop: 6,
  },
  textAreaLarge: {
    minHeight: 100,
    textAlignVertical: "top",
    paddingTop: 6,
  },
  documentsGrid: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  documentCard: {
    width: "23%",
    height: 84,
    backgroundColor: "#EFEFF0",
    borderRadius: 12,
    overflow: "hidden",
  },
  documentImage: {
    width: "100%",
    height: "100%",
  },
  documentFileContent: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "space-between",
    padding: 8,
  },
  documentName: {
    color: "#052D50",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "500",
  },
  documentTypeBadge: {
    color: "#052D50",
    fontSize: 10,
    fontWeight: "700",
  },
  projectPickerOverlay: {
    flex: 1,
    backgroundColor: "rgba(5, 45, 80, 0.28)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  projectPickerCard: {
    width: "100%",
    maxWidth: 420,
    maxHeight: "75%",
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  projectPickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  projectPickerTitle: {
    color: "#052D50",
    fontSize: 18,
    fontWeight: "600",
  },
  projectPickerClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(5, 45, 80, 0.06)",
  },
  projectPickerList: {
    width: "100%",
  },
  projectPickerListContent: {
    gap: 8,
  },
  projectPickerEmpty: {
    color: "#698196",
    fontSize: 15,
    textAlign: "center",
    paddingVertical: 20,
  },
  projectPickerItem: {
    minHeight: 58,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "rgba(5, 45, 80, 0.04)",
    borderWidth: 1,
    borderColor: "rgba(5, 45, 80, 0.06)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  projectPickerItemSelected: {
    borderColor: "#0091FF",
    backgroundColor: "rgba(0, 145, 255, 0.08)",
  },
  projectPickerItemText: {
    flex: 1,
  },
  projectPickerItemTitle: {
    color: "#052D50",
    fontSize: 16,
    fontWeight: "600",
  },
  projectPickerItemSubtitle: {
    color: "#698196",
    fontSize: 13,
    marginTop: 2,
  },
  createButton: {
    height: 56,
    marginTop: 12,
    marginBottom: 16,
    borderRadius: 18,
    backgroundColor: "#0091FF",
    alignItems: "center",
    justifyContent: "center",
  },
  createButtonDisabled: {
    opacity: 0.7,
  },
  createButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  datePickerOverlay: {
    flex: 1,
    backgroundColor: "rgba(5, 45, 80, 0.28)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  datePickerCard: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  datePickerTitle: {
    color: "#052D50",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 12,
  },
  datePickerButton: {
    marginTop: 12,
    alignSelf: "center",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "#0091FF",
  },
  datePickerButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  scheduleRow: {
    minHeight: 56,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e9e9e9",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  scheduleLabel: {
    color: "#052D50",
    fontSize: 16,
    fontFamily: "DMSans-Regular",
  },
  allDayTextContainer: {
    flex: 1,
    paddingRight: 12,
  },
  allDayHint: {
    color: "#698196",
    fontSize: 12,
    marginTop: 2,
  },
  dateChips: {
    flexDirection: "row",
    flexShrink: 1,
    gap: 8,
  },
  dateChip: {
    backgroundColor: "#7676801F",
    paddingHorizontal: 12,
    height: 34,
    borderRadius: 17,
    justifyContent: "center",
  },
  dateChipText: {
    color: "#052D50",
    fontSize: 14,
    fontFamily: "DMSans-Regular",
  },
  dateChipPlaceholder: {
    color: "rgba(5, 45, 80, 0.45)",
  },
  sheetOverlay: {
    flex: 1,
    backgroundColor: "rgba(5, 45, 80, 0.32)",
    justifyContent: "flex-end",
  },
  sheetBackdrop: {
    flex: 1,
  },
  sheetCard: {
    maxHeight: "88%",
    backgroundColor: "#EEF5FB",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
  },
  sheetHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: "rgba(5, 45, 80, 0.22)",
    alignSelf: "center",
    marginBottom: 12,
  },
  sheetHeader: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  sheetTitle: {
    color: "#052D50",
    fontSize: 20,
    fontFamily: "DMSans-SemiBold",
  },
  sheetCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(5, 45, 80, 0.06)",
  },
  sheetScroll: {
    width: "100%",
  },
  sheetContent: {
    paddingBottom: 16,
  },
  sheetSection: {
    marginBottom: 16,
  },
  sheetSectionTitle: {
    color: "#052D50",
    fontSize: 16,
    fontFamily: "DMSans-SemiBold",
    marginBottom: 8,
  },
  sheetGroupCard: {
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  notificationRow: {
    minHeight: 68,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e9e9e9",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sheetSearchBar: {
    height: 48,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 10,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  sheetSearchInput: {
    flex: 1,
    color: "#052D50",
    fontSize: 15,
  },
  sheetLoadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 18,
    gap: 8,
  },
  sheetLoadingText: {
    color: "#698196",
    fontSize: 13,
  },
  sheetEmptyText: {
    color: "#698196",
    fontSize: 13,
    textAlign: "center",
    paddingVertical: 18,
  },
  workerPickerList: {
    gap: 8,
    marginTop: 10,
  },
  workerPickerItem: {
    minHeight: 62,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  workerAvatarPlaceholder: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#D9E8F5",
    alignItems: "center",
    justifyContent: "center",
  },
  workerAvatarInitials: {
    color: "#052D50",
    fontSize: 13,
    fontFamily: "DMSans-SemiBold",
  },
  workerPickerText: {
    flex: 1,
  },
  workerName: {
    color: "#052D50",
    fontSize: 15,
    fontFamily: "DMSans-SemiBold",
    marginBottom: 2,
  },
  workerRole: {
    color: "#698196",
    fontSize: 13,
  },
  workerCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: "rgba(5, 45, 80, 0.18)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  workerCheckboxSelected: {
    backgroundColor: "#0091FF",
    borderColor: "#0091FF",
  },
  messageBox: {
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 22,
    padding: 16,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  notificationMessageInput: {
    minHeight: 44,
  },
  repeatDescription: {
    color: "#698196",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  repeatCard: {
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#FFFFFF",
  },
  repeatOptionRow: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e9e9e9",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  repeatOptionTitle: {
    color: "#052D50",
    fontSize: 15,
    fontFamily: "DMSans-SemiBold",
    marginBottom: 4,
  },
  repeatOptionTitleDisabled: {
    color: "rgba(5, 45, 80, 0.45)",
  },
  repeatOptionHint: {
    color: "#698196",
    fontSize: 12,
    lineHeight: 17,
  },
  repeatOptionHintDisabled: {
    color: "rgba(105, 129, 150, 0.8)",
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#C5D4E2",
    alignItems: "center",
    justifyContent: "center",
  },
  radioOuterSelected: {
    borderColor: "#0091FF",
  },
  radioOuterDisabled: {
    opacity: 0.55,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: "#0091FF",
  },
  intervalBox: {
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 22,
    padding: 16,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#FFFFFF",
    gap: 8,
  },
  intervalInput: {
    height: 46,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(5, 45, 80, 0.12)",
    paddingHorizontal: 14,
    color: "#052D50",
    fontSize: 16,
    fontFamily: "DMSans-Medium",
  },
  sheetDoneButton: {
    height: 54,
    borderRadius: 18,
    backgroundColor: "#0091FF",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  sheetDoneButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: "DMSans-SemiBold",
  },
});
