import { StyleSheet } from "react-native";

// Extracted from ChatConversationScreen.jsx — themed style factory (c = theme.content).
export const createStyles = (c) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.background,
    },
    backgroundBlur: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: 172,
      zIndex: 1,
    },
    header: {
      width: "100%",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingTop: 48,
      paddingBottom: 24,
      zIndex: 2,
      position: "relative",
    },
    headerInfo: {
      flex: 1,
      alignItems: "center",
      paddingHorizontal: 12,
    },
    channelName: {
      width: "100%",
      textAlign: "center",
      color: c.textPrimary,
      fontSize: 17,
      fontFamily: "DMSans-SemiBold",
    },
    channelStatus: {
      width: "100%",
      textAlign: "center",
      color: c.textPrimary,
      fontSize: 12,
    },
    backAvatar: {
      width: 44,
      height: 44,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 9999,
      backgroundColor: c.surfaceMuted,
      borderWidth: 1,
      borderColor: "#FFFFFF",
    },
    avatarImage: {
      width: "100%",
      height: "100%",
      borderRadius: 999,
    },
    avatarInitials: {
      width: "100%",
      height: "100%",
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarInitialsText: {
      color: "#FFFFFF",
      fontSize: 17,
      fontWeight: "700",
    },
    messagesContainer: {
      flex: 1,
      width: "100%",
      paddingTop: 120,
      paddingHorizontal: 12,
      zIndex: 0,
    },
    messagesContent: {
      paddingBottom: 16,
    },
    centeredContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 24,
    },
    statusText: {
      marginTop: 12,
      color: c.textMuted,
      textAlign: "center",
    },
    emptyState: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 16,
      padding: 20,
      borderWidth: 1,
      borderColor: "#FFFFFF",
    },
    emptyStateTitle: {
      color: c.textPrimary,
      fontSize: 18,
      marginBottom: 6,
    },
    emptyStateText: {
      color: c.textMuted,
    },
    translateToggle: {
      alignSelf: "center",
      backgroundColor: c.surfaceMuted,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 6,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: "#FFFFFF",
    },
    translateToggleText: {
      color: c.textPrimary,
      fontSize: 12,
      fontFamily: "DMSans-SemiBold",
    },
    translatedHint: {
      fontSize: 10,
      marginTop: 4,
    },
    myTranslatedHint: {
      color: "#ffffffcc",
    },
    otherTranslatedHint: {
      color: "#0785F4",
    },
    daySeparator: {
      alignSelf: "center",
      backgroundColor: c.surfaceMuted,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 5,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: "#FFFFFF",
    },
    daySeparatorText: {
      color: c.textPrimary,
      fontSize: 12,
      fontFamily: "DMSans-SemiBold",
    },
    messageRow: {
      marginBottom: 12,
    },
    myMessageRow: {
      alignItems: "flex-end",
    },
    otherMessageRow: {
      alignItems: "flex-start",
    },
    messageBubble: {
      padding: 12,
      borderRadius: 12,
      maxWidth: "70%",
    },
    // Image-only messages: drop the colored bubble so the photo shows on its own.
    mediaBubble: {
      padding: 0,
      backgroundColor: "transparent",
      borderWidth: 0,
      borderRadius: 18,
      overflow: "hidden",
    },
    attachmentsMedia: {
      marginBottom: 0,
      gap: 0,
    },
    mediaTimeOverlay: {
      position: "absolute",
      right: 8,
      bottom: 8,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 999,
      backgroundColor: "rgba(5, 45, 80, 0.45)",
    },
    mediaTimeText: {
      color: "#FFFFFF",
      fontSize: 10,
    },
    myMessageBubble: {
      backgroundColor: "#0785F4",
      borderBottomRightRadius: 0,
    },
    otherMessageBubble: {
      backgroundColor: c.surfaceMuted,
      borderBottomLeftRadius: 0,
      borderWidth: 1,
      borderColor: "#FFFFFF",
    },
    senderName: {
      color: c.textMuted,
      fontSize: 11,
      marginBottom: 4,
    },
    attachments: {
      gap: 6,
      marginBottom: 4,
    },
    attachmentImage: {
      width: 220,
      height: 220,
      borderRadius: 18,
      backgroundColor: "rgba(0,0,0,0.05)",
    },
    attachmentFile: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 10,
      backgroundColor: "rgba(0,0,0,0.06)",
      maxWidth: 220,
    },
    attachmentFileName: {
      color: c.textPrimary,
      fontSize: 13,
    },
    myMessageText: {
      color: "#ffffff",
      fontSize: 14,
    },
    otherMessageText: {
      color: c.textPrimary,
      fontSize: 14,
    },
    myMessageDate: {
      color: "#ffffff50",
      fontSize: 10,
      textAlign: "right",
      marginTop: 4,
    },
    otherMessageDate: {
      color: "#ADB5BD",
      fontSize: 10,
      textAlign: "right",
      marginTop: 4,
    },
    inputContainer: {
      width: "100%",
      flexDirection: "row",
      gap: 8,
      paddingHorizontal: 12,
      paddingBottom: 24,
      backgroundColor: c.background,
    },
    inputButton: {
      width: 48,
      height: 48,
      borderRadius: 999,
      backgroundColor: c.surfaceMuted,
      borderWidth: 1,
      borderColor: "#FFFFFF",
      alignItems: "center",
      justifyContent: "center",
    },
    inputIcon: {
      width: 24,
      height: 24,
    },
    textInputWrapper: {
      minHeight: 48,
      flex: 1,
      borderRadius: 9999,
      // Match the "+" attach button on the left.
      backgroundColor: c.surfaceMuted,
      borderWidth: 1,
      borderColor: "#FFFFFF",
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
    },
    textInput: {
      flex: 1,
      padding: 0,
      fontSize: 14,
      color: c.textPrimary,
      maxHeight: 96,
    },
    sendButton: {
      padding: 4,
    },
    sendIcon: {
      width: 24,
      height: 24,
    },
    voiceIcon: {
      width: 24,
      height: 24,
    },
    sheetBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0, 0, 0, 0.35)",
    },
    sheetBackdropPress: {
      flex: 1,
    },
    sheet: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: c.background,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 36,
    },
    sheetHandle: {
      alignSelf: "center",
      width: 40,
      height: 5,
      borderRadius: 999,
      backgroundColor: "rgba(5, 45, 80, 0.18)",
      marginBottom: 14,
    },
    sheetTitle: {
      textAlign: "center",
      fontSize: 13,
      letterSpacing: 0.3,
      color: "#8895A7",
      fontFamily: "DMSans-SemiBold",
      marginBottom: 12,
    },
    // Grouped iOS-style card holding the options; white rows on the light sheet.
    sheetCard: {
      backgroundColor: c.surface,
      borderRadius: 20,
      overflow: "hidden",
      marginBottom: 10,
    },
    sheetOption: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      paddingVertical: 14,
      paddingHorizontal: 14,
    },
    sheetDivider: {
      height: 1,
      marginLeft: 72,
      backgroundColor: "rgba(5, 45, 80, 0.07)",
    },
    sheetIcon: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    sheetIconCamera: {
      backgroundColor: "rgba(7, 133, 244, 0.12)",
    },
    sheetIconFile: {
      backgroundColor: "rgba(147, 51, 234, 0.12)",
    },
    sheetOptionCopy: {
      flex: 1,
    },
    sheetOptionText: {
      fontSize: 16,
      color: c.textPrimary,
      fontFamily: "DMSans-SemiBold",
    },
    sheetOptionHint: {
      fontSize: 13,
      color: "#8895A7",
      marginTop: 2,
    },
    sheetCancel: {
      height: 54,
      borderRadius: 18,
      backgroundColor: c.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    sheetCancelText: {
      fontSize: 16,
      color: c.textPrimary,
      fontFamily: "DMSans-SemiBold",
    },
  });
